-- Arquivo: inserir_ingredientes.sql

USE Cozzinhe; -- Seleciona o banco de dados

-- Insere os ingredientes na tabela ingredients
INSERT INTO ingredients (id_ingredients, nome)
VALUES
(1, 'a.1. original sauce'),
(2, 'apple'),
(3, 'apple cider vinegar'),
(4, 'bacon'),
(5, 'baking soda'),
(6, 'bananas'),
(7, 'black pepper'),
(8, 'brown sugar'),
(9, 'burnet root'),
(10, 'butter'),
(11, 'cake flour'),
(12, 'cheddar cheese'),
(13, 'cheese'),
(14, 'chicken bouillon cubes'),
(15, 'chicken rice soup'),
(16, 'chili powder'),
(17, 'chocolate sandwich style cookies'),
(18, 'chocolate syrup'),
(19, 'cinnamon oil'),
(20, 'cinnamon sticks'),
(21, 'clove oil'),
(22, 'collard greens'),
(23, 'cornstarch'),
(24, 'cracked black pepper'),
(25, 'cumin'),
(26, 'dark brown sugar'),
(27, 'diced tomatoes'),
(28, 'dry mustard'),
(29, 'eggs'),
(30, 'extra virgin olive oil'),
(31, 'fennel seeds'),
(32, 'flour'),
(33, 'fresh cilantro leaves'),
(34, 'fresh coarse ground black pepper'),
(35, 'fresh garlic'),
(36, 'fresh ginger'),
(37, 'fresh lemon juice'),
(38, 'frozen apple juice concentrate'),
(39, 'garlic'),
(40, 'garlic powder'),
(41, 'gentian root'),
(42, 'great northern bean'),
(43, 'green olives'),
(44, 'ground beef'),
(45, 'ground cumin'),
(46, 'ham hock'),
(47, 'honey'),
(48, 'hot sauce'),
(49, 'kidney beans'),
(50, 'lean pork chops'),
(51, 'lettuce'),
(52, 'liquid smoke'),
(53, 'milk'),
(54, 'mirin'),
(55, 'molasses'),
(56, 'mustard powder'),
(57, 'new potatoes'),
(58, 'oil'),
(59, 'olive oil'),
(60, 'onion'),
(61, 'orange juice'),
(62, 'orange rind'),
(63, 'orange, juice of'),
(64, 'parsley'),
(65, 'pepper'),
(66, 'peppercorn'),
(67, 'pork spareribs'),
(68, 'powdered sugar'),
(69, 'prepared horseradish'),
(70, 'prepared pizza crust'),
(71, 'red bell pepper'),
(72, 'red chile'),
(73, 'red wine vinegar'),
(74, 'ripe olives'),
(75, 'rotel tomatoes'),
(76, 'salt'),
(77, 'salt and pepper'),
(78, 'sausage patty'),
(79, 'scullcap herb'),
(80, 'shallots'),
(81, 'sour cream'),
(82, 'soy sauce'),
(83, 'spearmint'),
(84, 'spreadable cheese with garlic and herbs'),
(85, 'strawberry'),
(86, 'strawberry ice cream'),
(87, 'sugar'),
(88, 'tarragon'),
(89, 'tomato juice'),
(90, 'tomato paste'),
(91, 'tomato sauce'),
(92, 'tomato soup'),
(93, 'unsalted butter'),
(94, 'vanilla ice cream'),
(95, 'vanilla wafers'),
(96, 'walnuts'),
(97, 'water'),
(98, 'whipped cream'),
(99, 'whipping cream'),
(100, 'whiskey'),
(101, 'white vinegar'),
(102, 'whole berry cranberry sauce'),
(103, 'wood bethony'),
(104, 'yellow bell pepper'),
(105, 'yellow onion'),
(106, 'yellow onions');
